import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { RecoilRoot } from "recoil";
import { Provider } from "./provider";
import Cart from "@/components/Cart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Provider>
        <body className=" overflow-x-hidden">
          <Cart />
          {children}

          <Footer />
        </body>
      </Provider>
    </html>
  );
}
